env:
  - CGO_ENABLED=0
  - PROJECT=github.com/cloudradar-monitoring/rportcli
builds:
  - id: rportcli
    main: ./
    binary: rportcli
    ldflags:
      - "-s -w -X {{.Env.PROJECT}}/cmd.Version={{.Version}}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm64
archives:
  - id: rportcli
    builds:
      - rportcli
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
release:
  github:
    owner: cloudradar-monitoring
    name: rportcli
  draft: true
  prerelease: true
