name: Lint docs
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  docs:
    name: Lint docs
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Markdown Lint
        run: |
          cd docs
          npx markdownlint-cli  content/