name: Test
on: [push]
jobs:
  sca:
    name: Sca
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45
          args: -c .golangci.yml
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          go test -race -coverprofile=profile.cov ./...
          cat profile.cov
